import { lib, game, ui, get, ai, _status } from "../../../noname.js";
import { broadcastAll } from "../../../mode/guozhan/src/patch/game.js";

const qiaojian = [
  //黑桃普通
  ["spade", 1, "shandian"],
  ["spade", 1, "xietianzi"],
  ["spade", 1, "juedou"],
  ["spade", 2, "bagua"],
  ["spade", 2, "heiguangkai"],
  ["spade", 2, "cixiong"],
  ["spade", 2, "taigongyinfu"],
  ["spade", 3, "zhujinqiyuan", null, ["yingbian_zhuzhan", "yingbian_add"]],
  ["spade", 3, "huoshaolianying"],
  ["spade", 3, "shuiyanqijunx", null, ["yingbian_zhuzhan", "yingbian_add"]],
  ["spade", 4, "guohe"],
  ["spade", 4, "sha"],
  ["spade", 4, "shuiyanqijunx", null, ["yingbian_zhuzhan", "yingbian_add"]],
  ["spade", 5, "jueying"],
  ["spade", 5, "qinglong"],
  ["spade", 5, "sha"],
  ["spade", 6, "qinggang"],
  ["spade", 6, "jiu"],
  ["spade", 6, "sha", "ice"],
  ["spade", 7, "sha"],
  ["spade", 7, "sha"],
  ["spade", 7, "sha", "ice"],
  ["spade", 8, "sha", "ice"],
  ["spade", 8, "sha", "ice"],
  ["spade", 8, "sha"],
  ["spade", 9, "jiu"],
  ["spade", 9, "sha", "thunder"],
  ["spade", 9, "sha"],
  ["spade", 10, "bingliang"],
  ["spade", 10, "sha", "thunder"],
  ["spade", 10, "sha", null, ["yingbian_canqu", "yingbian_add"]],
  ["spade", 11, "wuxie", null, ["yingbian_kongchao", "yingbian_draw"]],
  ["spade", 11, "sha", null, ["yingbian_canqu", "yingbian_add"]],
  ["spade", 11, "sha", "thunder"],
  ["spade", 12, "zhangba"],
  ["spade", 12, "lulitongxin"],
  ["spade", 12, "tiesuo"],
  ["spade", 13, "wutiesuolian"],
  ["spade", 13, "wuxie"],
  ["spade", 13, "nanman", null, ["yingbian_fujia", "yingbian_remove"]],
  //草花普通
  ["club", 1, "juedou"],
  ["club", 1, "yuxi"],
  ["club", 1, "huxinjing"],
  ["club", 2, "sha"],
  ["club", 2, "tianjitu"],
  ["club", 2, "renwang"],
  ["club", 2, "tengjia"],
  ["club", 3, "sha"],
  ["club", 3, "chiling"],
  ["club", 3, "zhibi"],
  ["club", 4, "sha", null, ["yingbian_kongchao", "yingbian_add"]],
  ["club", 4, "sha", "thunder"],
  ["club", 4, "zhibi"],
  ["club", 5, "sha", null, ["yingbian_kongchao", "yingbian_add"]],
  ["club", 5, "sha", "thunder"],
  ["club", 5, "tongque"],
  ["club", 6, "sha", "thunder"],
  ["club", 6, "sha", null, ["yingbian_kongchao", "yingbian_add"]],
  ["club", 6, "lebu"],
  ["club", 7, "sha", "thunder"],
  ["club", 7, "sha"],
  ["club", 7, "nanman", null, ["yingbian_fujia", "yingbian_remove"]],
  ["club", 8, "sha", "thunder"],
  ["club", 8, "sha", null, ["yingbian_canqu", "yingbian_add"]],
  ["club", 8, "sha"],
  ["club", 9, "sha"],
  ["club", 9, "jiu"],
  ["club", 9, "jiu"],
  ["club", 10, "bingliang"],
  ["club", 10, "lulitongxin"],
  ["club", 10, "sha"],
  ["club", 11, "sha"],
  ["club", 11, "huoshaolianying"],
  ["club", 11, "sha"],
  ["club", 12, "zhujinqiyuan", null, ["yingbian_zhuzhan", "yingbian_add"]],
  ["club", 12, "jiedao", null, ["yingbian_fujia", "yingbian_hit"]],
  ["club", 12, "tiesuo"],
  ["club", 13, "tiesuo"],
  ["club", 13, "wuxie", null, ["guo"]],
  ["club", 13, "wuxie", null, ["guo"]],
  //红桃普通
  // ["heart", 1, "wanjian"],
  // ["heart", 1, "taoyuan"],
  // ["heart", 1, "lianjunshengyan"],
  // ["heart", 2, "shan"],
  // ["heart", 2, "chuqibuyi", null, ["yingbian_zhuzhan", "yingbian_add"]],
  // ["heart", 2, "diaohulishan"],
  // ["heart", 3, "chuqibuyi", null, ["yingbian_zhuzhan", "yingbian_add"]],
  // ["heart", 3, "wugu"],
  // ["heart", 3, "jingfanma"],
  // ["heart", 4, "tao"],
  // ["heart", 4, "sha", "fire", ["yingbian_canqu", "yingbian_damage"]],
  // ["heart", 4, "shan"],
  // ["heart", 5, "qilin"],
  // ["heart", 5, "chitu"],
  // ["heart", 5, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
  // ["heart", 6, "lebu"],
  // ["heart", 6, "tao"],
  // ["heart", 6, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
  // ["heart", 7, "tao"],
  // ["heart", 7, "dongzhuxianji"],
  // ["heart", 7, "shan"],
  // ["heart", 8, "tao"],
  // ["heart", 8, "dongzhuxianji"],
  // ["heart", 8, "tao"],
  // ["heart", 9, "tao"],
  // ["heart", 9, "yuanjiao"],
  // ["heart", 9, "tao"],
  // ["heart", 10, "sha"],
  // ["heart", 10, "shan"],
  // ["heart", 10, "sha"],
  // ["heart", 11, "yiyi"],
  // ["heart", 11, "tao"],
  // ["heart", 11, "sha", null, ["yingbian_zhuzhan", "yingbian_add"]],
  // ["heart", 12, "tao"],
  // ["heart", 12, "sha"],
  // ["heart", 12, "huoshaolianying"],
  // ["heart", 13, "zhuahuang"],
  // ["heart", 13, "shan"],
  // ["heart", 13, "huogong", null, ["yingbian_zhuzhan", "yingbian_add"]],
  // //方片普通
  // ["diamond", 1, "wuxinghelingshan"],
  // ["diamond", 1, "zhuge"],
  // ["diamond", 1, "xietianzi"],
  // ["diamond", 2, "shan"],
  // ["diamond", 2, "tao"],
  // ["diamond", 2, "tao"],
  // ["diamond", 3, "shunshou"],
  // ["diamond", 3, "shan"],
  // ["diamond", 3, "tao"],
  // ["diamond", 4, "yiyi"],
  // ["diamond", 4, "sha", "fire", ["yingbian_canqu", "yingbian_damage"]],
  // ["diamond", 4, "sha", "fire", ["yingbian_zhuzhan", "yingbian_add"]],
  // ["diamond", 5, "guanshi"],
  // ["diamond", 5, "sha", "fire"],
  // ["diamond", 5, "muniu"],
  // ["diamond", 6, "wuliu"],
  // ["diamond", 6, "shan"],
  // ["diamond", 6, "shan"],
  // ["diamond", 7, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
  // ["diamond", 7, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
  // ["diamond", 7, "shan"],
  // ["diamond", 8, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
  // ["diamond", 8, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
  // ["diamond", 8, "sha", "fire"],
  // ["diamond", 9, "jiu"],
  // ["diamond", 9, "shan"],
  // ["diamond", 9, "sha", "fire"],
  // ["diamond", 10, "shan"],
  // ["diamond", 10, "sha"],
  // ["diamond", 10, "diaohulishan"],
  // ["diamond", 11, "sha"],
  // ["diamond", 11, "shan"],
  // ["diamond", 11, "wuxie", null, ["guo"]],
  // ["diamond", 12, "sha"],
  // ["diamond", 12, "sanjian"],
  // ["diamond", 12, "wuxie", null, ["guo"]],
  // ["diamond", 12, "fangtian"],
  // ["diamond", 13, "zixin"],
  // ["diamond", 13, "shan"],
  // ["diamond", 13, "shan"],
];

